# Generated by Django 4.1.2 on 2022-10-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('numColMed', models.PositiveSmallIntegerField()),
                ('especialidad', models.CharField(max_length=50)),
                ('celular', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('DNI', models.PositiveSmallIntegerField()),
                ('edad', models.PositiveSmallIntegerField()),
                ('numHistoria', models.PositiveSmallIntegerField()),
                ('celular', models.PositiveSmallIntegerField()),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
    ]
